export type Auftrag = {
  id: number;
  verfahren: string[];
  material: string;
  length: number;
  width: number;
  height: number;
  masse: string;
  lieferDatum: Date;
  lieferArt: string;
  abholDatum: Date;
  abholArt: string;
  bilder: string[];
  dateien: string[];
  standort: string;
  benutzername: string;
  isSponsored: boolean;
  isBusiness: boolean;
};

// Berechnet das Lieferdatum basierend auf Werktagen
function berechneLieferdatum(werktage: number): Date {
  const date = new Date();
  let addedDays = 0;
  while (addedDays < werktage) {
    date.setDate(date.getDate() + 1);
    const day = date.getDay();
    if (day !== 0 && day !== 6) {
      addedDays++;
    }
  }
  return date;
}

export const dummyAuftraege = [{
        id: 1,
        
        verfahren: ['Pulverbeschichten'],
        material: 'Aluminium',
        length: 1000,
        width: 200,
        height: 50,
        masse: '5 kg',
        lieferDatum: berechneLieferdatum(3),
        lieferArt: 'Selbstanlieferung',
        abholDatum: berechneLieferdatum(6),
        abholArt: 'Selbstabholung',
        bilder: ['/images/baum1.jpg'],
        dateien: ['zeichnung.pdf', 'details.docx'],
        standort: 'Dornbirn',
        benutzername: 'Nutzer1',        
        isSponsored: true,
        isBusiness: true,
      },
      {
        id: 2,
        verfahren: ['Eloxieren'],
        material: 'Stahl',
        length: 800,
        width: 150,
        height: 40,
        masse: '4 kg',
        lieferDatum: berechneLieferdatum(3),
        lieferArt: 'Selbstabholung',
        abholDatum: berechneLieferdatum(8),
        abholArt: 'Anlieferung',
        bilder: ['/images/baum8.jpg'],
        dateien: ['bericht.pdf'],
        standort: 'Feldkirch',
        benutzername: 'Nutzer2',        
        isSponsored: false,
        isBusiness: false,
      },
      {
      id: 3,
      verfahren: ['Verzinken', 'Pulverbeschichten'],
      material: 'Aluminium',
      length: 1200,
      width: 250,
      height: 80,
      masse: '9 kg',
      lieferDatum: berechneLieferdatum(13),
      lieferArt: 'Selbstanlieferung',
      abholDatum: berechneLieferdatum(16),
      abholArt: 'Anlieferung',
      bilder: ['/images/baum3.jpg'],
      dateien: ['zeichnungen.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer3',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 4,
      verfahren: ['Eloxieren'],
      material: 'Stahl',
      length: 1000,
      width: 180,
      height: 50,
      masse: '6.5 kg',
      lieferDatum: berechneLieferdatum(8),
      lieferArt: 'Anlieferung',
      abholDatum: berechneLieferdatum(15),
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum4.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer4',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 5,
      verfahren: ['Pulverbeschichten', 'Eloxieren'],
      material: 'Aluminium',
      length: 1100,
      width: 150,
      height: 60,
      masse: '8 kg',
      lieferDatum: berechneLieferdatum(18),
      lieferArt: 'Selbstanlieferung',
      abholDatum: berechneLieferdatum(23),
      abholArt: 'Anlieferung',
      bilder: ['/images/baum5.jpg'],
      dateien: ['dokumentation.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer5',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 6,
      verfahren: ['Lackieren', 'Eloxieren'],
      material: 'Stahl',
      length: 1300,
      width: 220,
      height: 70,
      masse: '10 kg',
      lieferDatum: berechneLieferdatum(8),
      lieferArt: 'Selbstanlieferung',
      abholDatum: berechneLieferdatum(15),
      abholArt: 'Anlieferung',
      bilder: ['/images/baum6.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer6',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 7,
      verfahren: ['Entlacken', 'Pulverbeschichten'],
      material: 'Aluminium',
      length: 950,
      width: 180,
      height: 50,
      masse: '7 kg',
      lieferDatum: berechneLieferdatum(12),
      lieferArt: 'Selbstanlieferung',
      abholDatum: berechneLieferdatum(19),
      abholArt: 'Anlieferung',
      bilder: ['/images/baum7.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer7',
      isSponsored: false,
      isBusiness: true,
    },
    {
  id: 8,
  verfahren: ['Eloxieren', 'Pulverbeschichten'],
  material: 'Stahl',
  length: 850,
  width: 150,
  height: 50,
  masse: '8 kg',
  lieferDatum: berechneLieferdatum(33),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(38),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum8.jpg'],
  dateien: ['zeichnung.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer8',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 9,
  verfahren: ['Entlacken', 'Verzinken'],
  material: 'Aluminium',
  length: 1050,
  width: 180,
  height: 60,
  masse: '9 kg',
  lieferDatum: berechneLieferdatum(36),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(41),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum9.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer9',
  isSponsored: false,
  isBusiness: true,
},
{
  id: 10,
  verfahren: ['Pulverbeschichten', 'Folieren'],
  material: 'Stahl',
  length: 1200,
  width: 200,
  height: 60,
  masse: '8.5 kg',
  lieferDatum: berechneLieferdatum(39),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(44),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum10.jpg'],
  dateien: ['dokumentation.pdf'],
  standort: 'Bregenz',
  benutzername: 'Nutzer10',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 11,
  verfahren: ['Pulverbeschichten'],
  material: 'Aluminium',
  length: 900,
  width: 180,
  height: 55,
  masse: '7 kg',
  lieferDatum: berechneLieferdatum(43),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(48),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum22.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer11',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 12,
  verfahren: ['Eloxieren'],
  material: 'Stahl',
  length: 1000,
  width: 200,
  height: 40,
  masse: '6 kg',
  lieferDatum: berechneLieferdatum(46),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(51),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum12.jpg'],
  dateien: ['zeichnung.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer12',
  isSponsored: false,
  isBusiness: false,
},

    {
  id: 13,
  verfahren: ['Pulverbeschichten', 'Verzinken'],
  material: 'Aluminium',
  length: 1100,
  width: 230,
  height: 70,
  masse: '9.5 kg',
  lieferDatum: berechneLieferdatum(52),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(57),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum7.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer13',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 14,
  verfahren: ['Eloxieren', 'Pulverbeschichten'],
  material: 'Stahl',
  length: 950,
  width: 170,
  height: 60,
  masse: '8 kg',
  lieferDatum: berechneLieferdatum(55),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(60),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum14.jpg'],
  dateien: ['dokumentation.pdf'],
  standort: 'Bregenz',
  benutzername: 'Nutzer14',
  isSponsored: false,
  isBusiness: false,
},
{
  id: 15,
  verfahren: ['Pulverbeschichten', 'Folieren'],
  material: 'Aluminium',
  length: 1000,
  width: 220,
  height: 65,
  masse: '8 kg',
  lieferDatum: berechneLieferdatum(58),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(63),
  abholArt: 'Anlieferung',
  bilder: ['/images/apfel2.jpg'],
  dateien: ['zeichnung.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer15',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 16,
  verfahren: ['Entlacken'],
  material: 'Stahl',
  length: 1050,
  width: 190,
  height: 55,
  masse: '7.2 kg',
  lieferDatum: berechneLieferdatum(63),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(68),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum16.jpg'],
  dateien: ['bericht.docx'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer16',
  isSponsored: false,
  isBusiness: true,
},
{
  id: 17,
  verfahren: ['Pulverbeschichten', 'Eloxieren'],
  material: 'Aluminium',
  length: 1150,
  width: 210,
  height: 50,
  masse: '9 kg',
  lieferDatum: berechneLieferdatum(65),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(70),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum17.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Bregenz',
  benutzername: 'Nutzer17',
  isSponsored: false,
  isBusiness: false,
},
{
  id: 18,
  verfahren: ['Eloxieren', 'Verzinken'],
  material: 'Stahl',
  length: 1300,
  width: 240,
  height: 75,
  masse: '10 kg',
  lieferDatum: berechneLieferdatum(68),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(73),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum4.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer18',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 19,
  verfahren: ['Pulverbeschichten', 'Lackieren'],
  material: 'Aluminium',
  length: 900,
  width: 160,
  height: 60,
  masse: '6.8 kg',
  lieferDatum: berechneLieferdatum(71),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(76),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum19.jpg'],
  dateien: ['zeichnung.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer19',
  isSponsored: false,
  isBusiness: false,
},
{
  id: 20,
  verfahren: ['Eloxieren'],
  material: 'Stahl',
  length: 950,
  width: 210,
  height: 50,
  masse: '7 kg',
  lieferDatum: berechneLieferdatum(75),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(80),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum6.jpg'],
  dateien: ['bericht.docx'],
  standort: 'Bregenz',
  benutzername: 'Nutzer20',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 21,
  verfahren: ['Pulverbeschichten'],
  material: 'Aluminium',
  length: 950,
  width: 180,
  height: 65,
  masse: '6.5 kg',
  lieferDatum: berechneLieferdatum(82),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(86),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum42.jpg'],
  dateien: ['zeichnung.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer21',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 22,
  verfahren: ['Eloxieren'],
  material: 'Stahl',
  length: 1000,
  width: 220,
  height: 60,
  masse: '7.8 kg',
  lieferDatum: berechneLieferdatum(86),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(91),
  abholArt: 'Selbstabholung',
  bilder: ['/images/apfel1.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer22',
  isSponsored: false,
  isBusiness: false,
},

   {
  id: 23,
  verfahren: ['Pulverbeschichten', 'Verzinken'],
  material: 'Aluminium',
  length: 1100,
  width: 240,
  height: 55,
  masse: '9 kg',
  lieferDatum: berechneLieferdatum(94),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(98),
  abholArt: 'Anlieferung',
  bilder: ['/images/artikel13.jpg'],
  dateien: ['bericht.docx'],
  standort: 'Bregenz',
  benutzername: 'Nutzer23',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 24,
  verfahren: ['Pulverbeschichten', 'Folieren'],
  material: 'Stahl',
  length: 900,
  width: 190,
  height: 50,
  masse: '6.2 kg',
  lieferDatum: berechneLieferdatum(98),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(102),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum24.jpg'],
  dateien: ['zeichnung.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer24',
  isSponsored: false,
  isBusiness: true,
},
{
  id: 25,
  verfahren: ['Eloxieren'],
  material: 'Aluminium',
  length: 950,
  width: 210,
  height: 60,
  masse: '7 kg',
  lieferDatum: berechneLieferdatum(101),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(106),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum25.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer25',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 26,
  verfahren: ['Verzinken'],
  material: 'Stahl',
  length: 1050,
  width: 230,
  height: 55,
  masse: '8 kg',
  lieferDatum: berechneLieferdatum(106),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(111),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum26.jpg'],
  dateien: ['bericht.docx'],
  standort: 'Bregenz',
  benutzername: 'Nutzer26',
  isSponsored: false,
  isBusiness: false,
},
{
  id: 27,
  verfahren: ['Pulverbeschichten', 'Lackieren'],
  material: 'Aluminium',
  length: 1200,
  width: 240,
  height: 70,
  masse: '10 kg',
  lieferDatum: berechneLieferdatum(111),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(116),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum27.jpg'],
  dateien: ['dokumentation.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer27',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 28,
  verfahren: ['Pulverbeschichten', 'Eloxieren'],
  material: 'Aluminium',
  length: 1000,
  width: 200,
  height: 60,
  masse: '8 kg',
  lieferDatum: berechneLieferdatum(118),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(122),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum28.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Bregenz',
  benutzername: 'Nutzer28',
  isSponsored: false,
  isBusiness: true,
},
{
  id: 29,
  verfahren: ['Eloxieren'],
  material: 'Stahl',
  length: 1150,
  width: 230,
  height: 65,
  masse: '9.5 kg',
  lieferDatum: berechneLieferdatum(122),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(127),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum29.jpg'],
  dateien: ['bericht.docx'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer29',
  isSponsored: true,
  isBusiness: false,
},
{
  id: 30,
  verfahren: ['Pulverbeschichten'],
  material: 'Aluminium',
  length: 1100,
  width: 250,
  height: 50,
  masse: '7 kg',
  lieferDatum: berechneLieferdatum(127),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(132),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum30.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer30',
  isSponsored: false,
  isBusiness: true,
},
{
  id: 31,
  verfahren: ['Eloxieren', 'Verzinken'],
  material: 'Stahl',
  length: 1100,
  width: 220,
  height: 55,
  masse: '8.2 kg',
  lieferDatum: berechneLieferdatum(132),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(137),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum31.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer31',
  isSponsored: false,
  isBusiness: true,
},
{
  id: 32,
  verfahren: ['Pulverbeschichten'],
  material: 'Aluminium',
  length: 1050,
  width: 200,
  height: 50,
  masse: '6.5 kg',
  lieferDatum: berechneLieferdatum(137),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(142),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum32.jpg'],
  dateien: ['zeichnung.pdf'],
  standort: 'Bregenz',
  benutzername: 'Nutzer32',
  isSponsored: true,
  isBusiness: false,
},
{
  id: 33,
  verfahren: ['Eloxieren'],
  material: 'Stahl',
  length: 1000,
  width: 240,
  height: 60,
  masse: '7.5 kg',
  lieferDatum: berechneLieferdatum(142),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(147),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum33.jpg'],
  dateien: ['bericht.docx'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer33',
  isSponsored: false,
  isBusiness: true,
},

    {
  id: 34,
  verfahren: ['Pulverbeschichten', 'Lackieren'],
  material: 'Aluminium',
  length: 1200,
  width: 250,
  height: 70,
  masse: '10 kg',
  lieferDatum: berechneLieferdatum(147),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(151),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum34.jpg'],
  dateien: ['dokumentation.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer34',
  isSponsored: true,
  isBusiness: false,
},
{
  id: 35,
  verfahren: ['Eloxieren', 'Pulverbeschichten'],
  material: 'Aluminium',
  length: 1100,
  width: 210,
  height: 55,
  masse: '7.2 kg',
  lieferDatum: berechneLieferdatum(151),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(156),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum35.jpg'],
  dateien: ['bericht.docx'],
  standort: 'Bregenz',
  benutzername: 'Nutzer35',
  isSponsored: false,
  isBusiness: true,
},
{
  id: 36,
  verfahren: ['Verzinken'],
  material: 'Stahl',
  length: 950,
  width: 200,
  height: 50,
  masse: '6.5 kg',
  lieferDatum: berechneLieferdatum(156),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(161),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum36.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer36',
  isSponsored: true,
  isBusiness: false,
},
{
  id: 37,
  verfahren: ['Pulverbeschichten'],
  material: 'Stahl',
  length: 1000,
  width: 180,
  height: 55,
  masse: '6.9 kg',
  lieferDatum: berechneLieferdatum(161),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(166),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum37.jpg'],
  dateien: ['zeichnung.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer37',
  isSponsored: false,
  isBusiness: true,
},
{
  id: 38,
  verfahren: ['Eloxieren'],
  material: 'Aluminium',
  length: 950,
  width: 230,
  height: 60,
  masse: '7.3 kg',
  lieferDatum: berechneLieferdatum(166),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(171),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum38.jpg'],
  dateien: ['bericht.docx'],
  standort: 'Dornbirn',
  benutzername: 'Nutzer38',
  isSponsored: true,
  isBusiness: true,
},
{
  id: 39,
  verfahren: ['Pulverbeschichten'],
  material: 'Aluminium',
  length: 1200,
  width: 250,
  height: 65,
  masse: '8.5 kg',
  lieferDatum: berechneLieferdatum(171),
  lieferArt: 'Selbstanlieferung',
  abholDatum: berechneLieferdatum(176),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum39.jpg'],
  dateien: ['bericht.pdf'],
  standort: 'Bregenz',
  benutzername: 'Nutzer39',
  isSponsored: false,
  isBusiness: false,
},
{
  id: 40,
  verfahren: ['Eloxieren', 'Pulverbeschichten'],
  material: 'Stahl',
  length: 1000,
  width: 220,
  height: 55,
  masse: '7 kg',
  lieferDatum: berechneLieferdatum(176),
  lieferArt: 'Anlieferung',
  abholDatum: berechneLieferdatum(182),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum40.jpg'],
  dateien: ['dokumentation.pdf'],
  standort: 'Feldkirch',
  benutzername: 'Nutzer40',
  isSponsored: true,
  isBusiness: true,
}
,
  

      // Weitere Dummy-Daten hier hinzufügen...
    ];
