export const dummyAuftraege = [{
        id: 1,
        
        verfahren: ['Pulverbeschichten'],
        material: 'Aluminium',
        length: 1000,
        width: 200,
        height: 50,
        masse: '5 kg',
        lieferDatum: '2025-07-15',
        lieferArt: 'Selbstanlieferung',
        abholDatum: '2025-07-20',
        abholArt: 'Selbstabholung',
        bilder: ['/images/baum1.jpg'],
        dateien: ['zeichnung.pdf', 'details.docx'],
        standort: 'Dornbirn',
        benutzername: 'Nutzer1',
        bewertung: '4.5',
        isSponsored: true,
        isBusiness: true,
      },
      {
        id: 2,
        verfahren: ['Eloxieren'],
        material: 'Stahl',
        length: 800,
        width: 150,
        height: 40,
        masse: '4 kg',
        lieferDatum: '2025-07-18',
        lieferArt: 'Selbstabholung',
        abholDatum: '2025-07-22',
        abholArt: 'Anlieferung',
        bilder: ['/images/baum8.jpg'],
        dateien: ['bericht.pdf'],
        standort: 'Feldkirch',
        benutzername: 'Nutzer2',
        bewertung: '3.8',
        isSponsored: false,
        isBusiness: false,
      },
      {
      id: 3,
      verfahren: ['Verzinken', 'Pulverbeschichten'],
      material: 'Aluminium',
      length: 1200,
      width: 250,
      height: 80,
      masse: '9 kg',
      lieferDatum: '2025-07-22',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-07-26',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum3.jpg'],
      dateien: ['zeichnungen.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer3',
      bewertung: '4.7',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 4,
      verfahren: ['Eloxieren'],
      material: 'Stahl',
      length: 1000,
      width: 180,
      height: 50,
      masse: '6.5 kg',
      lieferDatum: '2025-07-24',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-07-29',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum4.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer4',
      bewertung: '4.3',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 5,
      verfahren: ['Pulverbeschichten', 'Eloxieren'],
      material: 'Aluminium',
      length: 1100,
      width: 150,
      height: 60,
      masse: '8 kg',
      lieferDatum: '2025-07-30',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-08-05',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum5.jpg'],
      dateien: ['dokumentation.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer5',
      bewertung: '4.8',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 6,
      verfahren: ['Lackieren', 'Eloxieren'],
      material: 'Stahl',
      length: 1300,
      width: 220,
      height: 70,
      masse: '10 kg',
      lieferDatum: '2025-08-05',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-08-10',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum6.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer6',
      bewertung: '4.6',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 7,
      verfahren: ['Entlacken', 'Pulverbeschichten'],
      material: 'Aluminium',
      length: 950,
      width: 180,
      height: 50,
      masse: '7 kg',
      lieferDatum: '2025-08-10',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-08-15',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum7.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer7',
      bewertung: '4.2',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 8,
      verfahren: ['Eloxieren', 'Pulverbeschichten'],
      material: 'Stahl',
      length: 850,
      width: 150,
      height: 50,
      masse: '8 kg',
      lieferDatum: '2025-08-12',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-08-17',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum8.jpg'],
      dateien: ['zeichnung.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer8',
      bewertung: '4.0',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 9,
      verfahren: ['Entlacken', 'Verzinken'],
      material: 'Aluminium',
      length: 1050,
      width: 180,
      height: 60,
      masse: '9 kg',
      lieferDatum: '2025-08-15',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-08-20',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum9.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer9',
      bewertung: '4.3',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 10,
      verfahren: ['Pulverbeschichten', 'Folieren'],
      material: 'Stahl',
      length: 1200,
      width: 200,
      height: 60,
      masse: '8.5 kg',
      lieferDatum: '2025-08-18',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-08-23',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum10.jpg'],
      dateien: ['dokumentation.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer10',
      bewertung: '4.5',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 11,
      verfahren: ['Pulverbeschichten'],
      material: 'Aluminium',
      length: 900,
      width: 180,
      height: 55,
      masse: '7 kg',
      lieferDatum: '2025-08-22',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-08-27',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum22.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer11',
      bewertung: '4.2',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 12,
      verfahren: ['Eloxieren'],
      material: 'Stahl',
      length: 1000,
      width: 200,
      height: 40,
      masse: '6 kg',
      lieferDatum: '2025-08-25',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-08-30',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum12.jpg'],
      dateien: ['zeichnung.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer12',
      bewertung: '4.0',
      isSponsored: false,
      isBusiness: false,
    },
    {
      id: 13,
      verfahren: ['Pulverbeschichten', 'Verzinken'],
      material: 'Aluminium',
      length: 1100,
      width: 230,
      height: 70,
      masse: '9.5 kg',
      lieferDatum: '2025-08-30',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-09-05',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum7.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer13',
      bewertung: '4.5',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 14,
      verfahren: ['Eloxieren', 'Pulverbeschichten'],
      material: 'Stahl',
      length: 950,
      width: 170,
      height: 60,
      masse: '8 kg',
      lieferDatum: '2025-09-02',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-09-07',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum14.jpg'],
      dateien: ['dokumentation.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer14',
      bewertung: '4.3',
      isSponsored: false,
      isBusiness: false,
    },
    {
      id: 15,
      verfahren: ['Pulverbeschichten', 'Folieren'],
      material: 'Aluminium',
      length: 1000,
      width: 220,
      height: 65,
      masse: '8 kg',
      lieferDatum: '2025-09-05',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-09-10',
      abholArt: 'Anlieferung',
      bilder: ['/images/apfel2.jpg'],
      dateien: ['zeichnung.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer15',
      bewertung: '4.6',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 16,
      verfahren: ['Entlacken'],
      material: 'Stahl',
      length: 1050,
      width: 190,
      height: 55,
      masse: '7.2 kg',
      lieferDatum: '2025-09-10',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-09-15',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum16.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer16',
      bewertung: '4.4',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 17,
      verfahren: ['Pulverbeschichten', 'Eloxieren'],
      material: 'Aluminium',
      length: 1150,
      width: 210,
      height: 50,
      masse: '9 kg',
      lieferDatum: '2025-09-12',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-09-17',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum17.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer17',
      bewertung: '4.1',
      isSponsored: false,
      isBusiness: false,
    },
    {
      id: 18,
      verfahren: ['Eloxieren', 'Verzinken'],
      material: 'Stahl',
      length: 1300,
      width: 240,
      height: 75,
      masse: '10 kg',
      lieferDatum: '2025-09-15',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-09-20',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum4.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer18',
      bewertung: '4.8',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 19,
      verfahren: ['Pulverbeschichten', 'Lackieren'],
      material: 'Aluminium',
      length: 900,
      width: 160,
      height: 60,
      masse: '6.8 kg',
      lieferDatum: '2025-09-18',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-09-23',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum19.jpg'],
      dateien: ['zeichnung.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer19',
      bewertung: '4.3',
      isSponsored: false,
      isBusiness: false,
    },
    {
      id: 20,
      verfahren: ['Eloxieren'],
      material: 'Stahl',
      length: 950,
      width: 210,
      height: 50,
      masse: '7 kg',
      lieferDatum: '2025-09-22',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-09-27',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum6.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Bregenz',
      benutzername: 'Nutzer20',
      bewertung: '4.2',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 21,
      verfahren: ['Pulverbeschichten'],
      material: 'Aluminium',
      length: 950,
      width: 180,
      height: 65,
      masse: '6.5 kg',
      lieferDatum: '2025-10-01',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-10-05',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum42.jpg'],
      dateien: ['zeichnung.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer21',
      bewertung: '4.3',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 22,
      verfahren: ['Eloxieren'],
      material: 'Stahl',
      length: 1000,
      width: 220,
      height: 60,
      masse: '7.8 kg',
      lieferDatum: '2025-10-05',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-10-10',
      abholArt: 'Selbstabholung',
      bilder: ['/images/apfel1.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer22',
      bewertung: '4.0',
      isSponsored: false,
      isBusiness: false,
    },
    {
      id: 23,
      verfahren: ['Pulverbeschichten', 'Verzinken'],
      material: 'Aluminium',
      length: 1100,
      width: 240,
      height: 55,
      masse: '9 kg',
      lieferDatum: '2025-10-08',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-10-12',
      abholArt: 'Anlieferung',
      bilder: ['/images/artikel13.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Bregenz',
      benutzername: 'Nutzer23',
      bewertung: '4.5',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 24,
      verfahren: ['Pulverbeschichten', 'Folieren'],
      material: 'Stahl',
      length: 900,
      width: 190,
      height: 50,
      masse: '6.2 kg',
      lieferDatum: '2025-10-12',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-10-16',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum24.jpg'],
      dateien: ['zeichnung.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer24',
      bewertung: '4.1',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 25,
      verfahren: ['Eloxieren'],
      material: 'Aluminium',
      length: 950,
      width: 210,
      height: 60,
      masse: '7 kg',
      lieferDatum: '2025-10-15',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-10-20',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum25.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer25',
      bewertung: '4.4',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 26,
      verfahren: ['Verzinken'],
      material: 'Stahl',
      length: 1050,
      width: 230,
      height: 55,
      masse: '8 kg',
      lieferDatum: '2025-10-20',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-10-25',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum26.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Bregenz',
      benutzername: 'Nutzer26',
      bewertung: '4.2',
      isSponsored: false,
      isBusiness: false,
    },
    {
      id: 27,
      verfahren: ['Pulverbeschichten', 'Lackieren'],
      material: 'Aluminium',
      length: 1200,
      width: 240,
      height: 70,
      masse: '10 kg',
      lieferDatum: '2025-10-25',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-10-30',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum27.jpg'],
      dateien: ['dokumentation.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer27',
      bewertung: '4.6',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 28,
      verfahren: ['Pulverbeschichten', 'Eloxieren'],
      material: 'Aluminium',
      length: 1000,
      width: 200,
      height: 60,
      masse: '8 kg',
      lieferDatum: '2025-11-01',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-11-05',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum28.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer28',
      bewertung: '4.3',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 29,
      verfahren: ['Eloxieren'],
      material: 'Stahl',
      length: 1150,
      width: 230,
      height: 65,
      masse: '9.5 kg',
      lieferDatum: '2025-11-05',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-11-10',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum29.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer29',
      bewertung: '4.7',
      isSponsored: true,
      isBusiness: false,
    },
    {
      id: 30,
      verfahren: ['Pulverbeschichten'],
      material: 'Aluminium',
      length: 1100,
      width: 250,
      height: 50,
      masse: '7 kg',
      lieferDatum: '2025-11-10',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-11-15',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum30.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer30',
      bewertung: '4.0',
      isSponsored: false,
      isBusiness: true,
    },

 
    {
      id: 31,
      verfahren: ['Eloxieren', 'Verzinken'],
      material: 'Stahl',
      length: 1100,
      width: 220,
      height: 55,
      masse: '8.2 kg',
      lieferDatum: '2025-11-15',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-11-20',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum31.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer31',
      bewertung: '4.1',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 32,
      verfahren: ['Pulverbeschichten'],
      material: 'Aluminium',
      length: 1050,
      width: 200,
      height: 50,
      masse: '6.5 kg',
      lieferDatum: '2025-11-20',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-11-25',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum32.jpg'],
      dateien: ['zeichnung.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer32',
      bewertung: '4.4',
      isSponsored: true,
      isBusiness: false,
    },
    {
      id: 33,
      verfahren: ['Eloxieren'],
      material: 'Stahl',
      length: 1000,
      width: 240,
      height: 60,
      masse: '7.5 kg',
      lieferDatum: '2025-11-25',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-11-30',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum33.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer33',
      bewertung: '4.6',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 34,
      verfahren: ['Pulverbeschichten', 'Lackieren'],
      material: 'Aluminium',
      length: 1200,
      width: 250,
      height: 70,
      masse: '10 kg',
      lieferDatum: '2025-12-01',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-12-05',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum34.jpg'],
      dateien: ['dokumentation.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer34',
      bewertung: '4.0',
      isSponsored: true,
      isBusiness: false,
    },
    {
      id: 35,
      verfahren: ['Eloxieren', 'Pulverbeschichten'],
      material: 'Aluminium',
      length: 1100,
      width: 210,
      height: 55,
      masse: '7.2 kg',
      lieferDatum: '2025-12-05',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-12-10',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum35.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Bregenz',
      benutzername: 'Nutzer35',
      bewertung: '4.5',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 36,
      verfahren: ['Verzinken'],
      material: 'Stahl',
      length: 950,
      width: 200,
      height: 50,
      masse: '6.5 kg',
      lieferDatum: '2025-12-10',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-12-15',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum36.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer36',
      bewertung: '4.2',
      isSponsored: true,
      isBusiness: false,
    },
    {
      id: 37,
      verfahren: ['Pulverbeschichten'],
      material: 'Stahl',
      length: 1000,
      width: 180,
      height: 55,
      masse: '6.9 kg',
      lieferDatum: '2025-12-15',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-12-20',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum37.jpg'],
      dateien: ['zeichnung.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer37',
      bewertung: '4.3',
      isSponsored: false,
      isBusiness: true,
    },
    {
      id: 38,
      verfahren: ['Eloxieren'],
      material: 'Aluminium',
      length: 950,
      width: 230,
      height: 60,
      masse: '7.3 kg',
      lieferDatum: '2025-12-20',
      lieferArt: 'Anlieferung',
      abholDatum: '2025-12-25',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum38.jpg'],
      dateien: ['bericht.docx'],
      standort: 'Dornbirn',
      benutzername: 'Nutzer38',
      bewertung: '4.1',
      isSponsored: true,
      isBusiness: true,
    },
    {
      id: 39,
      verfahren: ['Pulverbeschichten'],
      material: 'Aluminium',
      length: 1200,
      width: 250,
      height: 65,
      masse: '8.5 kg',
      lieferDatum: '2025-12-25',
      lieferArt: 'Selbstanlieferung',
      abholDatum: '2025-12-30',
      abholArt: 'Anlieferung',
      bilder: ['/images/baum39.jpg'],
      dateien: ['bericht.pdf'],
      standort: 'Bregenz',
      benutzername: 'Nutzer39',
      bewertung: '4.7',
      isSponsored: false,
      isBusiness: false,
    },
    {
      id: 40,
      verfahren: ['Eloxieren', 'Pulverbeschichten'],
      material: 'Stahl',
      length: 1000,
      width: 220,
      height: 55,
      masse: '7 kg',
      lieferDatum: '2025-12-30',
      lieferArt: 'Anlieferung',
      abholDatum: '2026-01-05',
      abholArt: 'Selbstabholung',
      bilder: ['/images/baum40.jpg'],
      dateien: ['dokumentation.pdf'],
      standort: 'Feldkirch',
      benutzername: 'Nutzer40',
      bewertung: '4.2',
      isSponsored: true,
      isBusiness: true,
    },
  

      // Weitere Dummy-Daten hier hinzufügen...
    ];
