export type Auftrag = {
  id: number;
  verfahren: {
    name: string;
    felder: Record<string, any>;
  }[];
  material: string;
  length: number;
  width: number;
  height: number;
  masse: string;
  lieferdatum: Date;
  lieferArt: string;
  abholdatum: Date;
  abholArt: string;
  bilder: string[];
  dateien?: { name: string; url: string }[];
  standort: string;
  user: string;
  gesponsert?: boolean;
  gewerblich?: boolean;
  privat: boolean;
  beschreibung?: string;
};




// Berechnet das Lieferdatum basierend auf Werktagen
function berechneLieferdatum(werktage: number): Date {
  const date = new Date();
  let addedDays = 0;
  while (addedDays < werktage) {
    date.setDate(date.getDate() + 1);
    const day = date.getDay();
    if (day !== 0 && day !== 6) {
      addedDays++;
    }
  }
  return date;
}

export const dummyAuftraege = [{
  id: 1,
  verfahren: [
    {
      name: 'Pulverbeschichten',
      felder: {
        lackhersteller: 'Tiger',
        farbbezeichnung: 'RAL 7016',
        farbpalette: 'RAL',
        oberfläche: 'Glatt',
        glanzgrad: 'Matt',
        qualität: 'GSB',
        effekte: ['Metallic'],
        zusatz: 'UV-beständig',
        zertifizierungen: ['GSB', 'Qualicoat']
      }
    }
  ],
  material: 'Aluminium',
  length: 1000,
  width: 200,
  height: 50,
  masse: '5 kg',
  lieferdatum: berechneLieferdatum(3),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(6),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum1.jpg'],
  dateien: [
    { name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' },
    { name: 'details.docx', url: '/uploads/details.docx' }
  ],
  standort: 'Dornbirn',
  user: 'Schlosserei Kalb - 4.5',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluminiumprofile sollen in RAL 7016 (Anthrazitgrau), glatt matt pulverbeschichtet werden. Anforderungen: UV-beständig, metallic Effekt, zertifiziert nach GSB und Qualicoat.'
},

  {
  id: 2,
  verfahren: [
    {
      name: 'Eloxieren',
      felder: {
        schichtdicke: '15 – 25 µm',
        passivierung: 'Chromatfrei Nachaluminat',
        härte: 'HV 150–200',
        farbton: 'Natural Aluminium',
        glanzgrad: 'Satin',
        zusatz: 'Korrosionsschutzklasse C3',
        saettigung: 'gleichmäßig'
      }
    }
  ],
  material: 'Stahl',
  length: 800,
  width: 150,
  height: 40,
  masse: '4 kg',
  lieferdatum: berechneLieferdatum(3),
  lieferArt: 'Selbstabholung',
  abholdatum: berechneLieferdatum(8),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum8.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Feldkirch',
  user: 'Eloxal müller',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Stahlteile zur Eloxierung – robust, einfache Geometrie, bereit zur Vorbehandlung.',
},


{
  id: 3,
  verfahren: [
    {
      name: 'Verzinken',
      felder: {
        zinktyp: 'Sendzimierverfahren',
        schichtdicke: '20 – 30 µm',
        passivierung: 'Chromatfrei Nachbehandlung',
        korrosionsschutzklasse: 'C3',
        härte: 'HV 100'
      }
    },
    {
      name: 'Pulverbeschichten',
      felder: {
        lackhersteller: 'Tiger',
        farbbezeichnung: 'RAL 7016',
        farbpalette: 'RAL',
        oberfläche: 'Glatt',
        glanzgrad: 'Matt',
        qualität: 'GSB',
        effekte: ['Metallic'],
        zusatz: 'UV-beständig',
        zertifizierungen: ['GSB', 'Qualicoat']
      }
    }
  ],
  material: 'Aluminium',
  length: 1200,
  width: 250,
  height: 80,
  masse: '9 kg',
  lieferdatum: berechneLieferdatum(13),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(16),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum3.jpg'],
  dateien: [{ name: 'zeichnungen.pdf', url: '/uploads/zeichnungen.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer3',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Alu-Bauteile, verzinkt und anschliessend pulverbeschichtet – korrosionsgeschützt.',
},
{
  id: 4,
  verfahren: [
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Stahl',
  length: 1000,
  width: 180,
  height: 50,
  masse: '6.5 kg',
  lieferdatum: berechneLieferdatum(8),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(15),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum4.jpg'],
  dateien: [{ name: 'bericht.docx', url: '/uploads/bericht.docx' }],
  standort: 'Feldkirch',
  user: 'Nutzer4',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlkomponenten zur Eloxierung – gleichmäßige Oberfläche für Schutzschicht.',
}
,
{
  id: 5,
  verfahren: [
    { name: 'Eloxieren', felder: {} },
    { name: 'Pulverbeschichten', felder: {} }    
  ],
  material: 'Aluminium',
  length: 1100,
  width: 150,
  height: 60,
  masse: '8 kg',
  lieferdatum: berechneLieferdatum(18),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(23),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum5.jpg'],
  dateien: [{ name: 'dokumentation.pdf', url: '/uploads/dokumentation.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer5',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluprofile zur Eloxierung und anschließenden Pulverbeschichtung – duales Verfahren.',
}
,
{
  id: 6,
  verfahren: [
    { name: 'Lackieren', felder: {} },
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Stahl',
  length: 1300,
  width: 220,
  height: 70,
  masse: '10 kg',
  lieferdatum: berechneLieferdatum(8),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(15),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum6.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer6',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlteile, die lackiert und eloxiert werden sollen – widerstandsfähig gegen Witterung.',
},
    {
  id: 7,
  verfahren: [
    { name: 'Entlacken', felder: {} },
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Aluminium',
  length: 950,
  width: 180,
  height: 50,
  masse: '7 kg',
  lieferdatum: berechneLieferdatum(12),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(19),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum7.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer7',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Alubauteile zur Entlackung und Pulverbeschichtung – hochwertige Wiederaufbereitung.',
},
    {
  id: 8,
  verfahren: [
    { name: 'Eloxieren', felder: {} },
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Stahl',
  length: 850,
  width: 150,
  height: 50,
  masse: '8 kg',
  lieferdatum: berechneLieferdatum(33),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(38),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum8.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer8',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlteile mit Eloxal- und Pulverbeschichtung – hohe Lebensdauer gewünscht.',
}
,
{
  id: 9,
  verfahren: [
    { name: 'Entlacken', felder: {} },
    { name: 'Verzinken', felder: {} }
  ],
  material: 'Aluminium',
  length: 1050,
  width: 180,
  height: 60,
  masse: '9 kg',
  lieferdatum: berechneLieferdatum(36),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(41),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum9.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer9',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluprofile mit Entlackung und anschließendem Verzinken – Rostschutz im Fokus.',
}
,
{
  id: 10,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} },
    { name: 'Folieren', felder: {} }
  ],
  material: 'Stahl',
  length: 1200,
  width: 200,
  height: 60,
  masse: '8.5 kg',
  lieferdatum: berechneLieferdatum(39),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(44),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum10.jpg'],
  dateien: [{ name: 'dokumentation.pdf', url: '/uploads/dokumentation.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer10',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlteile mit Pulverbeschichtung und dekorativer Folierung – optisch und funktional.',
}
,
{
  id: 11,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Aluminium',
  length: 900,
  width: 180,
  height: 55,
  masse: '7 kg',
  lieferdatum: berechneLieferdatum(43),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(48),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum22.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer11',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluminiumteile zur klassischen Pulverbeschichtung – farblich neutral in Anthrazit.',
},
{
  id: 12,
  verfahren: [
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Stahl',
  length: 1000,
  width: 200,
  height: 40,
  masse: '6 kg',
  lieferdatum: berechneLieferdatum(46),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(51),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum12.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer12',
  gesponsert: false,
  gewerblich: false,
  privat: false,
  beschreibung: 'Stahlmaterial zur Eloxierung – gleichmäßige Oberfläche und Schutz vor Oxidation.',
},

  {
  id: 13,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} },
    { name: 'Verzinken', felder: {} }
  ],
  material: 'Aluminium',
  length: 1100,
  width: 230,
  height: 70,
  masse: '9.5 kg',
  lieferdatum: berechneLieferdatum(52),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(57),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum7.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer13',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluprofile mit Pulverbeschichtung und Verzinkung – doppelte Schutzfunktion.',
},
{
  id: 14,
  verfahren: [
    { name: 'Eloxieren', felder: {} },
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Stahl',
  length: 950,
  width: 170,
  height: 60,
  masse: '8 kg',
  lieferdatum: berechneLieferdatum(4),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(12),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum14.jpg'],
  dateien: [{ name: 'dokumentation.pdf', url: '/uploads/dokumentation.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer14',
  gesponsert: false,
  gewerblich: false,
  privat: false,
  beschreibung: 'Stahlteile zur Eloxierung und Pulverbeschichtung – kombinierter Oberflächenschutz.',
},
{
  id: 15,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} },
    { name: 'Folieren', felder: {} }
  ],
  material: 'Aluminium',
  length: 1000,
  width: 220,
  height: 65,
  masse: '8 kg',
  lieferdatum: berechneLieferdatum(58),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(63),
  abholArt: 'Anlieferung',
  bilder: ['/images/apfel2.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer15',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluteile zur Pulverbeschichtung und Folierung – technische und dekorative Anwendung.',
},

{
  id: 16,
  verfahren: [
    { name: 'Entlacken', felder: {} }
  ],
  material: 'Stahl',
  length: 1050,
  width: 190,
  height: 55,
  masse: '7.2 kg',
  lieferdatum: berechneLieferdatum(63),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(68),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum16.jpg'],
  dateien: [{ name: 'bericht.docx', url: '/uploads/bericht.docx' }],
  standort: 'Feldkirch',
  user: 'Nutzer16',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlprofile zur Entlackung – vorbereitend für spätere Nachbearbeitung.',
},
{
  id: 17,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} },
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Aluminium',
  length: 1150,
  width: 210,
  height: 50,
  masse: '9 kg',
  lieferdatum: berechneLieferdatum(65),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(70),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum17.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer17',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Aluminiumteile für Pulverbeschichtung und Eloxierung – funktionaler Korrosionsschutz.',
},
{
  id: 18,
  verfahren: [
    { name: 'Eloxieren', felder: {} },
    { name: 'Verzinken', felder: {} }
  ],
  material: 'Stahl',
  length: 1300,
  width: 240,
  height: 75,
  masse: '10 kg',
  lieferdatum: berechneLieferdatum(16),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(24),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum4.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer18',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlteile zur Eloxierung und Verzinkung – maximierte Widerstandsfähigkeit.',
},
{
  id: 19,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} },
    { name: 'Lackieren', felder: {} }
  ],
  material: 'Aluminium',
  length: 900,
  width: 160,
  height: 60,
  masse: '6.8 kg',
  lieferdatum: berechneLieferdatum(71),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(76),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum19.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer19',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Aluteile mit Pulverbeschichtung und zusätzlicher Lackierung – optisch hochwertig.',
},

{
  id: 20,
  verfahren: [
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Stahl',
  length: 950,
  width: 210,
  height: 50,
  masse: '7 kg',
  lieferdatum: berechneLieferdatum(75),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(80),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum6.jpg'],
  dateien: [{ name: 'bericht.docx', url: '/uploads/bericht.docx' }],
  standort: 'Bregenz',
  user: 'Nutzer20',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlkomponenten für Eloxierung – dekorativ und schützend für den Außeneinsatz.',
},
{
  id: 21,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Aluminium',
  length: 950,
  width: 180,
  height: 65,
  masse: '6.5 kg',
  lieferdatum: berechneLieferdatum(82),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(86),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum42.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer21',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Alubauteile zur Pulverbeschichtung – wetterfest, optisch modern.',
},
{
  id: 22,
  verfahren: [
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Stahl',
  length: 1000,
  width: 220,
  height: 60,
  masse: '7.8 kg',
  lieferdatum: berechneLieferdatum(86),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(91),
  abholArt: 'Selbstabholung',
  bilder: ['/images/apfel1.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer22',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Stahlteile mit Eloxierung – Oberfläche mit hohem Korrosionsschutz.',
},
{
  id: 23,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} },
    { name: 'Verzinken', felder: {} }
  ],
  material: 'Aluminium',
  length: 1100,
  width: 240,
  height: 55,
  masse: '9 kg',
  lieferdatum: berechneLieferdatum(94),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(98),
  abholArt: 'Anlieferung',
  bilder: ['/images/artikel13.jpg'],
  dateien: [{ name: 'bericht.docx', url: '/uploads/bericht.docx' }],
  standort: 'Bregenz',
  user: 'Nutzer23',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluminiumteile zum Verzinken und Pulverbeschichten – doppelte Schutzmaßnahme.',
},
{
  id: 24,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} },
    { name: 'Folieren', felder: {} }
  ],
  material: 'Stahl',
  length: 900,
  width: 190,
  height: 50,
  masse: '6.2 kg',
  lieferdatum: berechneLieferdatum(98),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(102),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum24.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer24',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlteile mit Pulverbeschichtung und Folierung – für technische Anwendungen.',
},
{
  id: 25,
  verfahren: [
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Aluminium',
  length: 950,
  width: 210,
  height: 60,
  masse: '7 kg',
  lieferdatum: berechneLieferdatum(101),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(106),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum25.jpg'],
  dateien: [{ name: 'bericht.pdf', url: '/uploads/bericht.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer25',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluprofile zur Eloxierung – für gleichmäßige, langlebige Oberflächen.',
},
{
  id: 26,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Stahl',
  length: 1020,
  width: 200,
  height: 55,
  masse: '7.4 kg',
  lieferdatum: berechneLieferdatum(104),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(109),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum26.jpg'],
  dateien: [{ name: 'zeichnung.dxf', url: '/uploads/zeichnung.dxf' }],
  standort: 'Bregenz',
  user: 'Nutzer26',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Stahlteile zur Pulverbeschichtung – stoßfest und wetterbeständig.',
},
{
  id: 27,
  verfahren: [
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Aluminium',
  length: 880,
  width: 180,
  height: 50,
  masse: '6.7 kg',
  lieferdatum: berechneLieferdatum(107),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(112),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum27.jpg'],
  dateien: [{ name: 'beschreibung.pdf', url: '/uploads/beschreibung.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer27',
  gesponsert: true,
  gewerblich: false,
  privat: true,
  beschreibung: 'Alubauteile mit Eloxierung – klassische Schutzschicht für Außeneinsatz.',
},
{
  id: 28,
  verfahren: [
    { name: 'Entlacken', felder: {} },
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Stahl',
  length: 970,
  width: 210,
  height: 60,
  masse: '8.3 kg',
  lieferdatum: berechneLieferdatum(110),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(115),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum28.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer28',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlteile zur Entlackung und Pulverbeschichtung – zur Wiederverwertung vorbereitet.',
},
{
  id: 29,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Aluminium',
  length: 910,
  width: 190,
  height: 55,
  masse: '7 kg',
  lieferdatum: berechneLieferdatum(113),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(118),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum29.jpg'],
  dateien: [{ name: 'details.pdf', url: '/uploads/details.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer29',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluminiumkomponenten zur Pulverbeschichtung – moderne, matte Optik.',
},
{
  id: 30,
  verfahren: [
    { name: 'Eloxieren', felder: {} },
    { name: 'Lackieren', felder: {} }
  ],
  material: 'Stahl',
  length: 1000,
  width: 200,
  height: 60,
  masse: '8.1 kg',
  lieferdatum: berechneLieferdatum(116),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(121),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum30.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer30',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Stahlteile mit Eloxierung und Lackierung – funktionell und optisch ansprechend.',
},
{
  id: 31,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Aluminium',
  length: 960,
  width: 180,
  height: 55,
  masse: '6.6 kg',
  lieferdatum: berechneLieferdatum(119),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(124),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum31.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer31',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluprofile zur Pulverbeschichtung – ideal für architektonische Anwendungen.',

},
{
  id: 32,
  verfahren: [
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Stahl',
  length: 890,
  width: 190,
  height: 50,
  masse: '6.9 kg',
  lieferdatum: berechneLieferdatum(122),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(127),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum32.jpg'],
  dateien: [{ name: 'plan.dxf', url: '/uploads/plan.dxf' }],
  standort: 'Feldkirch',
  user: 'Nutzer32',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Stahlbauteile mit Eloxierung – gleichmäßige, matte Schutzschicht geplant.',
},
{
  id: 33,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} },
    { name: 'Verzinken', felder: {} }
  ],
  material: 'Aluminium',
  length: 1000,
  width: 210,
  height: 60,
  masse: '7.5 kg',
  lieferdatum: berechneLieferdatum(126),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(130),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum33.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer33',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluteile zur Pulverbeschichtung und Verzinkung – perfekter Korrosionsschutz.',
},
{
  id: 34,
  verfahren: [
    { name: 'Folieren', felder: {} }
  ],
  material: 'Stahl',
  length: 920,
  width: 200,
  height: 55,
  masse: '7.1 kg',
  lieferdatum: berechneLieferdatum(129),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(134),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum34.jpg'],
  dateien: [{ name: 'beschreibung.pdf', url: '/uploads/beschreibung.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer34',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlteile mit dekorativer Folierung – für optisch anspruchsvolle Projekte.',
},
{
  id: 35,
  verfahren: [
    { name: 'Eloxieren', felder: {} },
    { name: 'Lackieren', felder: {} }
  ],
  material: 'Aluminium',
  length: 970,
  width: 220,
  height: 65,
  masse: '8.4 kg',
  lieferdatum: berechneLieferdatum(132),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(137),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum35.jpg'],
  dateien: [{ name: 'plan.pdf', url: '/uploads/plan.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer35',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluminium mit Eloxierung und Lackierung – Funktion und Design vereint.',
},
{
  id: 36,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Stahl',
  length: 940,
  width: 210,
  height: 60,
  masse: '7.9 kg',
  lieferdatum: berechneLieferdatum(135),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(140),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum36.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer36',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Aluminium mit Eloxierung und Lackierung – Funktion und Design vereint.',
},
{
  id: 37,
  verfahren: [
    { name: 'Eloxieren', felder: {} }
  ],
  material: 'Aluminium',
  length: 880,
  width: 180,
  height: 50,
  masse: '6.5 kg',
  lieferdatum: berechneLieferdatum(138),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(143),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum37.jpg'],
  dateien: [{ name: 'beschreibung.docx', url: '/uploads/beschreibung.docx' }],
  standort: 'Feldkirch',
  user: 'Nutzer37',
  gesponsert: true,
  gewerblich: false,
  privat: true,
  beschreibung: 'Alubauteile zur Eloxierung – saubere Oberfläche mit Schutzfunktion.',
},

{
  id: 38,
  verfahren: [
    { name: 'Entlacken', felder: {} },
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Stahl',
  length: 990,
  width: 220,
  height: 65,
  masse: '8.6 kg',
  lieferdatum: berechneLieferdatum(141),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(146),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum38.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Dornbirn',
  user: 'Nutzer38',
  gesponsert: false,
  gewerblich: true,
  privat: false,
  beschreibung: 'Stahlteile zur Entlackung und anschließender Pulverbeschichtung – ideal zur Wiederaufbereitung.',
},
{
  id: 39,
  verfahren: [
    { name: 'Pulverbeschichten', felder: {} }
  ],
  material: 'Aluminium',
  length: 930,
  width: 210,
  height: 60,
  masse: '7.3 kg',
  lieferdatum: berechneLieferdatum(144),
  lieferArt: 'Selbstanlieferung',
  abholdatum: berechneLieferdatum(149),
  abholArt: 'Anlieferung',
  bilder: ['/images/baum39.jpg'],
  dateien: [{ name: 'details.pdf', url: '/uploads/details.pdf' }],
  standort: 'Bregenz',
  user: 'Nutzer39',
  gesponsert: true,
  gewerblich: true,
  privat: false,
  beschreibung: 'Aluteile zur Pulverbeschichtung – langlebige und farbbeständige Oberfläche.',
},
{
  id: 40,
  verfahren: [
    { name: 'Eloxieren', felder: {} },
    { name: 'Lackieren', felder: {} }
  ],
  material: 'Stahl',
  length: 980,
  width: 220,
  height: 65,
  masse: '8.2 kg',
  lieferdatum: berechneLieferdatum(147),
  lieferArt: 'Anlieferung',
  abholdatum: berechneLieferdatum(152),
  abholArt: 'Selbstabholung',
  bilder: ['/images/baum40.jpg'],
  dateien: [{ name: 'zeichnung.pdf', url: '/uploads/zeichnung.pdf' }],
  standort: 'Feldkirch',
  user: 'Nutzer40',
  gesponsert: false,
  gewerblich: false,
  privat: true,
  beschreibung: 'Stahlkomponenten mit Eloxierung und Lackierung – industrielle Oberfläche mit Schutzwirkung.',
}

      // Weitere Dummy-Daten hier hinzufügen...
    ];
